# Form implementation generated from reading ui file 'c:\Users\mkami\Documents\Apps\MPC_Interface\Interface\Graph.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GraphDialog(object):
    def setupUi(self, GraphDialog):
        GraphDialog.setObjectName("GraphDialog")
        GraphDialog.resize(746, 414)
        GraphDialog.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"border-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(127, 172, 177);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(GraphDialog)
        self.buttonBox.setGeometry(QtCore.QRect(650, 10, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(GraphDialog)
        self.buttonBox.accepted.connect(GraphDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(GraphDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GraphDialog)

    def retranslateUi(self, GraphDialog):
        _translate = QtCore.QCoreApplication.translate
        GraphDialog.setWindowTitle(_translate("GraphDialog", "Dialog"))
